/**
 * @author Zulkarnain Shah
 * @date 18-Jul-2017
 */

package messageapi.controllers;

import java.util.UUID;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import messageapi.models.Employee;
import messageapi.repositories.EmployeeRepository;

@RestController
public class EmployeeController {
	
	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private EmployeeRepository employeeRepository;
	
	@RequestMapping(value="/employee/post",method= RequestMethod.POST)
	public void post(@RequestBody Employee employee) {
		if(employee.getEmp_ID() == null) {
			employee.setEmp_ID(UUID.randomUUID().toString());
		}
		employeeRepository.save(employee);
	}
	
	@RequestMapping(value="/employee/getEmployee",method= RequestMethod.GET,produces="application/json")
	public Employee get(@RequestParam(value="emp_ID") String emp_ID) {
		Employee employee = employeeRepository.getEmployeeByEmpID(emp_ID);
		return employee;
	}
}
